import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { SessionProvider } from 'next-auth/react'
import './globals.css'
import { auth } from '@/lib/auth'
import { Toaster } from '@/components/ui/sonner'
import Navbar from '@/components/navbar/navbar'
import Providers from '@/components/providers'
import Footer from '@/components/footer'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Next Blog',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const session = await auth()

  return (
    <SessionProvider session={session}>
      <html lang='en'>
        <body className={inter.className}>
          <Providers>
            <main className='min-h-[100svh] flex flex-col'>
              <Navbar />
              {children}
              <Toaster />
              <Footer />
            </main>
          </Providers>
        </body>
      </html>
    </SessionProvider>
  )
}
